[php]
extensions = [
  "gd",
  "bcmath",
  "ctype",
  "curl",
  "dom",
  "exif",
  "fileinfo",
  "intl",
  "mbstring",
  "opcache",
  "pcntl",
  "pdo",
  "pdo_mysql",
  "redis",
  "tokenizer",
  "xml",
  "xmlwriter",
  "zip"
]
